
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./components/sessionProviderWrapper";
import useUserInfo from "./hooks/useUserInfo";
import LayoutDiv from "./components/layoutDiv";
import { AppProvider } from "./contexts/AppContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
 
}: Readonly<{
  children: React.ReactNode;
 
}>) {

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <SessionProviderWrapper> 
           
           <AppProvider>

          <div className=" ">
            {/* Left Sidebar */}
            {/* <div className="w-[28%]  ">
              
              <p>left</p>
            </div> */}
             
            {/* Main Content */}

              {children}
            

            {/* Right Sidebar */}
            {/* <div className="w-[28%] hidden md:block  ">
             
            </div> */}
          </div>
         
           </AppProvider>

           
          </SessionProviderWrapper> 
      
       
      </body>
    </html>
  );
}
